security:
  # Hashage des mots de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # User provider pour charger les utilisateurs depuis l'entity User
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      # Méthodes d'authentification
      form_login:
        login_path: login
        check_path: login
        default_target_path: dashboard
        username_parameter: email
        password_parameter: password

      logout:
        path: logout
        target: /

      # Activer la fonctionnalité switch_user pour permettre à un super admin de se connecter comme un autre utilisateur
      switch_user: true

  # Contrôle d’accès par rôle
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/dashboard, roles: ROLE_USER }
    - { path: ^/super-admin, roles: ROLE_SUPER_ADMIN }

# Configuration spécifique pour l'environnement de test
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # bcrypt lowest
        time_cost: 3 # argon2 lowest
        memory_cost: 10
