# config/packages/security.yaml
security:
  # 🔹 Hashage des mots de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # 🔹 User provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # 🔹 Hiérarchie des rôles
  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER]
    ROLE_ADMIN: [ROLE_USER]
    ROLE_COMMERCE: [ROLE_USER]

  # 🔹 Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      stateless: true

      # 🔹 Authentification via JSON login
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
        success_handler: App\Security\LoginSuccessHandler
        failure_handler: App\Security\LoginFailureHandler

      # 🔹 JWT authenticator pour toutes les routes protégées
      jwt: ~

      # 🔹 Optionnel : super admin peut switcher user
      switch_user: true

  # 🔹 Contrôle d’accès par rôle
  access_control:
    # Super admin
    - { path: ^/super-admin, roles: ROLE_SUPER_ADMIN }
    # Admin
    - { path: ^/admin, roles: ROLE_ADMIN }
    # Commerce
    - { path: ^/commerce, roles: ROLE_COMMERCE }
    # Tout utilisateur connecté
    - { path: ^/dashboard, roles: ROLE_USER }
    - { path: ^/commerce/dashboard, roles: ROLE_COMMERCE }
    # Pages accessibles sans authentification
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/register/commerce, roles: PUBLIC_ACCESS }
    - { path: ^/verify-email, roles: PUBLIC_ACCESS }
    - { path: ^/resend-code, roles: PUBLIC_ACCESS }

# 🔹 Configuration spécifique pour l'environnement de test
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # bcrypt minimal
        time_cost: 3 # argon2 minimal
        memory_cost: 10
