# config/services.yaml

parameters:
  # tes paramètres ici

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Services normaux
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
